### ISSUE TITLE
How to run this slurm code

### ISSUE THREAD

**Issue by yunh-w** [LayneH/GreenMIM#1]
Hi, I haven't used slum. Can you tell me how to configure the environment and what's the demo for running scripts?

**Comment by LayneH** [comment]
Hi,
I have updated the [instructions](https://github.com/LayneH/GreenMIM#for-non-slurm-users) for non-slurm users. Please refer to the instructions.

**Comment by LayneH** [comment]
Closed due to the inactivation.
