### ISSUE TITLE
How can l install the 'mc' modules which imported in the 'base_dataset.py' ?

### ISSUE THREAD

**Issue by Geek-Peng** [LayneH/GreenMIM#3]
Hi :
    Which packages should be installed when import the 'mc' module as in the  'base_dataset.py' ? I've not found the packages requirments file.
Many thanks!

**Comment by LayneH** [comment]
Hi,

Thanks for pointing it out.
Actually, the 'mc' module is an internal dependency, which is not required in this code.
I will modify this part and commit the changes.
