### ISSUE TITLE
MSSP-I is strongly NP-hard

### ISSUE THREAD

**Issue by YouJiacheng** [LayneH/GreenMIM#5]
Note: MSSP in following screen shot is actually MSSP-I
![image](https://user-images.githubusercontent.com/83971976/187024027-550843f8-59e2-4476-abfd-c67dcc59ed0d.png)

Caprara, Alberto; Kellerer, Hans; Pferschy, Ulrich (2000). The Multiple Subset Sum Problem. SIAM Journal on Optimization, 11(2), 308–319. doi:10.1137/s1052623498348481

How can a strongly NP-hard problem be solved in pseudo-polynomial time?

**Comment by YouJiacheng** [comment]
In [34](Cited in GreenMIM paper) H. Kellerer, U. Pferschy, and D. Pisinger. Knapsack problems. Springer, 2004:
![image](https://user-images.githubusercontent.com/83971976/187024578-6baaddc2-c829-457f-845b-929d48d5b9bb.png)

**Comment by YouJiacheng** [comment]
BTW, since the number of groups is not given and each window is required to be in one group. The problem is more similar to the Bin Packing Problem instead of the Multiple Subset Sum Problem.

**Comment by LayneH** [comment]
Hi,

I agree that the pointed sentence is not rigorous enough. What we tried to put forth there is that there exist multiple polynomial-time approximation schemes for MSSP-I. We will fix this part and make it more clear in the updated version.
Thanks for the note and for referring to Bin Packing Problem.
