### ISSUE TITLE
Visualize the results after training is wrong

### ISSUE THREAD

**Issue by Linzhou4869** [LayneH/GreenMIM#8]
Visualize the results after training, the results are blurry, and the part without the mask has changed

**Comment by LayneH** [comment]
Please first note that you need to revert [the normalization](https://github.com/LayneH/GreenMIM/blob/main/models_swin.py#L938) for the reconstructed image before visualization if you haven't done so.
In addition, it is expected that the unmasked portion will change after reconstruction, as suggested by the [code for visualization of MAE](https://github.com/facebookresearch/mae/blob/main/demo/mae_visualize.ipynb).
